/**
 * The AI sometimes puts placeholders ("N/A", "PENDING_REGISTRATION") or names ("SIRIM CoC Milesight UR35")
 * in the application reference field. A real reference is one token (no spaces) that contains a digit,
 * e.g. "SQAS/CMCS/2026/0012", "RAT-2026-0441" or a job number like "678371".
 * Returns the cleaned reference, or "" when it isn't a real one.
 */
export function cleanApplicationRef(ref?: string | null): string {
  const r = String(ref ?? '').trim();
  if (!r) return '';
  if (/^SQAS\/GEN\//i.test(r) || /^th_/i.test(r)) return ''; // generated by older versions of the tracker
  if (/\s/.test(r)) return '';
  if (!/\d/.test(r)) return '';
  if (/^(n\/?a|tba|tbc|none|null|unknown|pending.*|-+)$/i.test(r)) return '';
  if (r.length < 4 || r.length > 60) return '';
  return r;
}

export function displayApplicationRef(ref?: string | null): string {
  return cleanApplicationRef(ref) || 'No SIRIM ref yet';
}
